# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Laba2DBGUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(761, 760)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidgetUser = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetUser.setGeometry(QtCore.QRect(10, 50, 741, 221))
        self.tableWidgetUser.setRowCount(6)
        self.tableWidgetUser.setColumnCount(4)
        self.tableWidgetUser.setObjectName("tableWidgetUser")
        self.userTableName = QtWidgets.QLabel(self.centralwidget)
        self.userTableName.setGeometry(QtCore.QRect(260, 10, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.userTableName.setFont(font)
        self.userTableName.setObjectName("userTableName")
        self.usernameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.usernameLineEdit.setGeometry(QtCore.QRect(190, 300, 111, 31))
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.phoneLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.phoneLineEdit.setGeometry(QtCore.QRect(10, 300, 171, 31))
        self.phoneLineEdit.setObjectName("phoneLineEdit")
        self.tarifLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.tarifLineEdit.setGeometry(QtCore.QRect(620, 300, 61, 31))
        self.tarifLineEdit.setObjectName("tarifLineEdit")
        self.addressLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.addressLineEdit.setGeometry(QtCore.QRect(310, 300, 301, 31))
        self.addressLineEdit.setObjectName("addressLineEdit")
        self.tarifidLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.tarifidLineEdit.setGeometry(QtCore.QRect(10, 670, 61, 31))
        self.tarifidLineEdit.setObjectName("tarifidLineEdit")
        self.tarifnameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.tarifnameLineEdit.setGeometry(QtCore.QRect(90, 670, 111, 31))
        self.tarifnameLineEdit.setObjectName("tarifnameLineEdit")
        self.tarifButtonFind = QtWidgets.QPushButton(self.centralwidget)
        self.tarifButtonFind.setEnabled(False)
        self.tarifButtonFind.setGeometry(QtCore.QRect(10, 710, 75, 23))
        self.tarifButtonFind.setObjectName("tarifButtonFind")
        self.tarifpriceLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.tarifpriceLineEdit.setGeometry(QtCore.QRect(220, 670, 111, 31))
        self.tarifpriceLineEdit.setObjectName("tarifpriceLineEdit")
        self.tableWidgetTarif = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetTarif.setGeometry(QtCore.QRect(10, 420, 741, 221))
        self.tableWidgetTarif.setRowCount(6)
        self.tableWidgetTarif.setColumnCount(4)
        self.tableWidgetTarif.setObjectName("tableWidgetTarif")
        self.tarifTableName = QtWidgets.QLabel(self.centralwidget)
        self.tarifTableName.setGeometry(QtCore.QRect(290, 380, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tarifTableName.setFont(font)
        self.tarifTableName.setObjectName("tarifTableName")
        self.tarifButtonInsert = QtWidgets.QPushButton(self.centralwidget)
        self.tarifButtonInsert.setEnabled(False)
        self.tarifButtonInsert.setGeometry(QtCore.QRect(90, 710, 75, 23))
        self.tarifButtonInsert.setObjectName("tarifButtonInsert")
        self.tarifButtonDelete = QtWidgets.QPushButton(self.centralwidget)
        self.tarifButtonDelete.setEnabled(False)
        self.tarifButtonDelete.setGeometry(QtCore.QRect(170, 710, 75, 23))
        self.tarifButtonDelete.setObjectName("tarifButtonDelete")
        self.createdbButton = QtWidgets.QPushButton(self.centralwidget)
        self.createdbButton.setGeometry(QtCore.QRect(630, 710, 121, 23))
        self.createdbButton.setObjectName("createdbButton")
        self.tarifButtonClean = QtWidgets.QPushButton(self.centralwidget)
        self.tarifButtonClean.setEnabled(False)
        self.tarifButtonClean.setGeometry(QtCore.QRect(250, 710, 111, 23))
        self.tarifButtonClean.setObjectName("tarifButtonClean")
        self.deletedbButton = QtWidgets.QPushButton(self.centralwidget)
        self.deletedbButton.setEnabled(False)
        self.deletedbButton.setGeometry(QtCore.QRect(630, 680, 121, 23))
        self.deletedbButton.setObjectName("deletedbButton")
        self.tarifidLabel = QtWidgets.QLabel(self.centralwidget)
        self.tarifidLabel.setGeometry(QtCore.QRect(10, 650, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tarifidLabel.setFont(font)
        self.tarifidLabel.setObjectName("tarifidLabel")
        self.tarifnameLabel = QtWidgets.QLabel(self.centralwidget)
        self.tarifnameLabel.setGeometry(QtCore.QRect(90, 650, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tarifnameLabel.setFont(font)
        self.tarifnameLabel.setObjectName("tarifnameLabel")
        self.tarifpriceLabel = QtWidgets.QLabel(self.centralwidget)
        self.tarifpriceLabel.setGeometry(QtCore.QRect(220, 650, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tarifpriceLabel.setFont(font)
        self.tarifpriceLabel.setObjectName("tarifpriceLabel")
        self.userButtonClean = QtWidgets.QPushButton(self.centralwidget)
        self.userButtonClean.setEnabled(False)
        self.userButtonClean.setGeometry(QtCore.QRect(250, 340, 111, 23))
        self.userButtonClean.setObjectName("userButtonClean")
        self.userButtonInsert = QtWidgets.QPushButton(self.centralwidget)
        self.userButtonInsert.setEnabled(False)
        self.userButtonInsert.setGeometry(QtCore.QRect(90, 340, 75, 23))
        self.userButtonInsert.setObjectName("userButtonInsert")
        self.userButtonDelete = QtWidgets.QPushButton(self.centralwidget)
        self.userButtonDelete.setEnabled(False)
        self.userButtonDelete.setGeometry(QtCore.QRect(170, 340, 75, 23))
        self.userButtonDelete.setObjectName("userButtonDelete")
        self.userButtonFind = QtWidgets.QPushButton(self.centralwidget)
        self.userButtonFind.setEnabled(False)
        self.userButtonFind.setGeometry(QtCore.QRect(10, 340, 75, 23))
        self.userButtonFind.setObjectName("userButtonFind")
        self.deleteTablesButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteTablesButton.setEnabled(False)
        self.deleteTablesButton.setGeometry(QtCore.QRect(630, 650, 121, 23))
        self.deleteTablesButton.setObjectName("deleteTablesButton")
        self.userTarifLabel = QtWidgets.QLabel(self.centralwidget)
        self.userTarifLabel.setGeometry(QtCore.QRect(620, 280, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.userTarifLabel.setFont(font)
        self.userTarifLabel.setObjectName("userTarifLabel")
        self.usernameLabel = QtWidgets.QLabel(self.centralwidget)
        self.usernameLabel.setGeometry(QtCore.QRect(190, 280, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.usernameLabel.setFont(font)
        self.usernameLabel.setObjectName("usernameLabel")
        self.phoneLabel = QtWidgets.QLabel(self.centralwidget)
        self.phoneLabel.setGeometry(QtCore.QRect(10, 280, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.phoneLabel.setFont(font)
        self.phoneLabel.setObjectName("phoneLabel")
        self.addressLabel = QtWidgets.QLabel(self.centralwidget)
        self.addressLabel.setGeometry(QtCore.QRect(310, 280, 301, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.addressLabel.setFont(font)
        self.addressLabel.setObjectName("addressLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.userTableName.setText(_translate("MainWindow", "Таблица Пользователей"))
        self.tarifButtonFind.setText(_translate("MainWindow", "Найти"))
        self.tarifTableName.setText(_translate("MainWindow", "Таблица Тарифов"))
        self.tarifButtonInsert.setText(_translate("MainWindow", "Добавить"))
        self.tarifButtonDelete.setText(_translate("MainWindow", "Удалить"))
        self.createdbButton.setText(_translate("MainWindow", "Создать базу данных"))
        self.tarifButtonClean.setText(_translate("MainWindow", "Очистить таблицу"))
        self.deletedbButton.setText(_translate("MainWindow", "Удалить базу данных"))
        self.tarifidLabel.setText(_translate("MainWindow", "ID"))
        self.tarifnameLabel.setText(_translate("MainWindow", "Название Тарифа"))
        self.tarifpriceLabel.setText(_translate("MainWindow", "Оплата (за месяц)"))
        self.userButtonClean.setText(_translate("MainWindow", "Очистить таблицу"))
        self.userButtonInsert.setText(_translate("MainWindow", "Добавить"))
        self.userButtonDelete.setText(_translate("MainWindow", "Удалить"))
        self.userButtonFind.setText(_translate("MainWindow", "Найти"))
        self.deleteTablesButton.setText(_translate("MainWindow", "Удалить таблицы"))
        self.userTarifLabel.setText(_translate("MainWindow", "Тариф"))
        self.usernameLabel.setText(_translate("MainWindow", "ФИО"))
        self.phoneLabel.setText(_translate("MainWindow", "Номер"))
        self.addressLabel.setText(_translate("MainWindow", "Адрес"))
